Cards
pascalweber85/capstone-project pull request #4
Opened 2021-06-08 20:08 UTC by pascalweber85

ready for a review:)

2021-06-08 20:54 UTC, Morten-Moeller reviewed
Good job, added some small suggestions. 👾
Happy coding

2021-06-08 20:54 UTC, Morten-Moeller commented on src/components/Card.js
> +  justify-items: end;
justify-content is used for display flex.

2021-06-08 20:54 UTC, Morten-Moeller commented on src/components/Card.js
> +    width: 9em;
consider using ch instead of em for the width

2021-06-08 20:54 UTC, Morten-Moeller commented on src/components/Header.js
> +  font-family: Arial, Helvetica, sans-serif;
Didn't you set the font-family inside GlobalStyles?

2021-06-08 20:54 UTC, Morten-Moeller commented on src/pages/locationPage.js
> +          const { id, attributes } = location
you could de-structure in line 18 and you can on top de-structure attributes too

2021-06-09 09:58 UTC, macfrei requested changes
Well done, added a few comments you might want to consider! 🚀

2021-06-09 09:58 UTC, macfrei commented on src/GlobalStyle.js
> +   box-sizing: border-box
```suggestion
   box-sizing: border-box;
```

2021-06-09 09:58 UTC, macfrei commented on src/components/Card.js
> +export default function Card({ image, title, ratingimage, text }) {
To keep it in camelCase: `ratingImage`
```suggestion
export default function Card({ image, title, ratingImage, text }) {
```

2021-06-09 09:58 UTC, macfrei commented on src/components/Card.js
> +        <img src={ratingimage} alt="" />
Does `ratingImage` contain information about how the location is rated? Is there a rating displayed? If so, then the information should be provided in the `alt` attribute.

2021-06-09 09:58 UTC, macfrei commented on src/components/Card.spec.js
> +  })
I would test all props and with the right role.
```suggestion
  it('renders name of card', () => {
    render(<Card title="Völkerschlachtdenkmal" text="Lorem Ipsum"  image="path/to/image" ratingImage="path/to/Image" />)
    expect(screen.getByRole('heading', {name: 'Völkerschlachtdenkmal'})).toBeInTheDocument()
    ....
  })
```

2021-06-09 09:58 UTC, macfrei commented on src/components/Card.spec.js
> +  })
This does _not_ test the text! When you query be `getByRole('heading')` you get the `h2` element of your card.

2021-06-09 09:58 UTC, macfrei commented on src/components/Card.stories.js
> +  text: 'Sehenswürdigkeit',
These should be tested as well. Like I commented above.

2021-06-09 09:58 UTC, macfrei commented on src/components/Header.spec.js
> +    expect(screen.getByRole('heading')).toBeInTheDocument()
One of them is efficient enough.

2021-06-09 09:58 UTC, macfrei commented on src/data.json
> +    "type": "card",
What is `"type": "card"` for?

2021-06-09 09:58 UTC, macfrei commented on src/pages/locationPage.js
> +        })}
Could be shortened to this:
```suggestion
        {location.map(({id, {main_image_path, rating_image_path, title, text}}) => (
            <Card
              key={id}
              image={main_image_path}
              title={title}
              ratingimage={rating_image_path}
              text={text}
            />
          )
}
```

2021-06-09 09:58 UTC, macfrei commented on src/pages/locationPage.spec.js
> +})
Looks like you forgot to test it!

2021-06-09 09:58 UTC, macfrei commented on src/pages/locationPage.js
> +`
If you call it `Grid` I would expect that there is a grid but here is none.

2021-06-09 09:58 UTC, macfrei commented on src/pages/locationPage.js
> +export default function LocationPage({ title }) {
You don't use this title anywhere....
```suggestion
export default function LocationPage() {
```

2021-06-09 09:58 UTC, macfrei commented on src/pages/locationPage.stories.js
> +  title: 'All Locations',
This doesn't work, because you don't use it anywhere.

2021-06-14 08:31 UTC, merged